[package]
name = "schemers"
version = "0.1.0"
authors = ["Michael Bridgen <mikeb@squaremobius.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: port to 7.0.0.
rustyline = "1.0.0"
nom = "~6.0.0"
